name: "Lint"

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: write

jobs:
  ruff:
    name: "Ruff Lint & Format"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run Ruff check"
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: "Run Ruff formatter"
        uses: astral-sh/ruff-action@v3
        with:
          args: "format ."

      - name: "Auto Commit Formatting Changes"
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "style fixes by ruff"
